---
title: "R Notebook"
output: html_notebook
---



```{r}
library(ggplot2)
library(data.table)
library(RColorBrewer)
```


data format
1. *bracken.report
2. ` *kreport.bracken` contains species name and abundance

```{r}

datadir <- "Data/"
setwd("./")
bracken_data <- data.table()

data_processing <- function(iter=1,N=10,top_species=TRUE,threshold=0.001,human_removal=FALSE,file_prefix="zymo"){
  ifelse(iter==0,
         Bracken_file <- paste0(datadir,file_prefix,".kreport.bracken"),
         Bracken_file <- paste0(datadir,file_prefix,"_",iter,".kreport.bracken")
  )
  bracken_data <- fread(Bracken_file)
  
  ifelse(human_removal==TRUE,
         bracken_data <- bracken_data[name != "Homo sapiens"] %>%
           mutate(fraction_total_reads_percent = round(fraction_total_reads / sum(fraction_total_reads) * 100, 2)),
         bracken_data[, fraction_total_reads_percent := round(fraction_total_reads * 100, 2)]
         )
  
  #bracken_data[, Log_Abundance := log(fraction_total_reads + 1)]  

  if(top_species==TRUE){
    filtered_species <- bracken_data[order(-fraction_total_reads), head(.SD, n = N)]
    }else{
    filtered_species <- bracken_data[fraction_total_reads >= threshold]
    }

    
  genus_summary <- bracken_data[, .(Total_Reads = sum(fraction_total_reads * kraken_assigned_reads)), by = `taxonomy_id`]
  cumulative_abundance <- bracken_data[order(-fraction_total_reads), .(Cumulative_Abundance = cumsum(fraction_total_reads))]
  
  other_species <- bracken_data[!name %in% filtered_species$name]
  other_species$name <- "others"

  final_data <- rbind(filtered_species, other_species)
  final_data$name <- factor(final_data$name, levels = c("others","Homo sapiens",unique(final_data$name[
  final_data$name != "others" & 
    final_data$name != "Homo sapiens"])))

  final_data$sampleName <- paste0(file_prefix,iter)
  return(final_data)
}

```



```{r}



dt <- data.table()
for (i in 0:3) {
  dt_iter <- data_processing(iter=i,top_species = FALSE, threshold = 0.01,human_removal = TRUE)
  dt <- rbind(dt_iter,dt)
  
}


length(levels(dt$name))

paired_palette <- brewer.pal(name = "Set3", n = length(levels(dt$name)) +1 )
paired_palette <- paired_palette[paired_palette != "#D9D9D9"]
final_colors <- setNames(paired_palette, levels(dt$name))
final_colors["others"] <- "#a1a1a1"
final_colors["Homo sapiens"] <- "#D9D9D9"

ggplot(dt, aes(x = sampleName, y = fraction_total_reads_percent, fill = name)) +
  geom_bar(stat = "identity", position = "stack") +
  #coord_polar(theta = "y")+
  theme_minimal() +coord_flip()+
  labs(x = "Sample", y = "Abundance", fill= "Species",title = "Stacked Bar Plot of Species Abundance") +
  theme(axis.text.y = element_text(angle = 0, hjust = 1), 
        axis.title.y = element_text(face = "italic")
        ) +  
  scale_fill_manual(values = final_colors)

```


```{r}


dt_inner <- dt[sampleName=="zymo_0"] %>%
  mutate(sampleName = "",fraction_total_reads_percent = 0)

dt_combined <- rbind(dt,dt_inner)


ggplot(dt_combined, aes(x = sampleName, y = fraction_total_reads_percent, fill = name)) +
  geom_bar(stat = "identity",width = 0.62) +
  coord_polar(theta = "y")+
  theme_minimal() +
  labs(x = "Sample", y = "Abundance", fill = "Species" , title = "Stacked Ring Plot of Species Abundance") +
  theme(axis.text = element_blank(), 
        axis.ticks = element_blank(),
        #axis.line = element_line(color = "black"),
        panel.grid = element_blank()
        ) +  
  scale_fill_manual(values = final_colors) +
  ylim(c(0,133))+


  geom_text(aes(label = sampleName,y=0.1),
            #angle = 90,
            color = "black", 
            size = 3, 
            vjust = 1
  )
```


```{r}
ggplot(dt, aes(x = sampleName, y = name, fill = fraction_total_reads_percent)) +
  geom_tile() + 
  theme_minimal() +
  scale_fill_gradientn(colors = rev(brewer.pal(name = "Spectral",n=11)), na.value = "white")+  
  labs(x = "Sample", y = "Species", title = "Heatmap of Species Abundance",
       fill = "Abundance") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),  
        axis.text.y = element_text(angle = 0))

                               
```



PcoA

```{r}

library(vegan)
dt_clean <- dt[fraction_total_reads!=0]
abundance_matrix_clean <- dt_clean[, c("name", "fraction_total_reads")]
bray_dist <- vegdist(abundance_matrix_clean$fraction_total_reads, method = "bray")

pcoa_result <- cmdscale(1 - bray_dist, k = 2)

pcoa_result <- as.data.table(pcoa_result)
colnames(pcoa_result) <- c("PC1","PC2")


pcoa_result$sampleName <- as.factor(dt_clean$sampleName)



if (!requireNamespace("ellipse", quietly = TRUE)) install.packages("ellipse")
library(ellipse)


library(factoextra)


pcoa_data <- pcoa_result
pcoa_data$Cluster <- pcoa_data$sampleName
ggplot(pcoa_data,  aes(x = PC1, y = PC2,color=sampleName)) +
  geom_point(size=1) +
  stat_ellipse(geom="polygon",aes(fill = sampleName),alpha = 0.15,color=NA,level=0.998) +
  theme_minimal() +
  scale_color_manual(values = brewer.pal(name = "Set1",n=4))+
  scale_fill_manual(values = brewer.pal(name = "Set1",n=4))+
  labs(title = "PCoA with Clusters", x = "PCoA1", y = "PCoA2")


```


bowtie2

```{r}


dt <- data.table()
for (i in 0:3) {
  dt_iter <- data_processing(iter=i,top_species = FALSE, threshold = 0.01,human_removal = FALSE)
  dt <- rbind(dt_iter,dt)
  
}

for (i in 1:3) {
  dt_iter <- data_processing(iter=i,top_species = FALSE, threshold = 0.01,human_removal = FALSE,file_prefix = "zymo_rm_host_2")
  dt <- rbind(dt_iter,dt)
  
}

length(levels(dt$name))

paired_palette <- brewer.pal(name = "Set3", n = length(levels(dt$name)) +1 )
paired_palette <- paired_palette[paired_palette != "#D9D9D9"]
final_colors <- setNames(paired_palette, levels(dt$name))
final_colors["others"] <- "#a1a1a1"
final_colors["Homo sapiens"] <- "#D9D9D9"

ggplot(dt, aes(x = sampleName, y = fraction_total_reads_percent, fill = name)) +
  geom_bar(stat = "identity", position = "stack") +
  #coord_polar(theta = "y")+
  theme_minimal() +coord_flip()+
  labs(x = "Sample", y = "Abundance", fill= "Species",title = "Stacked Bar Plot of Species Abundance") +
  theme(axis.text.y = element_text(angle = 0, hjust = 1), 
        axis.title.y = element_text(face = "italic")
        ) +  
  scale_fill_manual(values = final_colors)


```

